### ISSUE TITLE
Add custom volumes defined in settings

### ISSUE THREAD

**Issue by leoyala** [CAMI-DKFZ/simpa#10]
Add the possibility to define custom volumes in settings, without the need to define an extra volume creator. This involves the checkup of the parsed volumes, they need to contain a minimum set of tags in order for the optical simulations to work.

**Comment by jgroehl** [comment]
Not sure what exactly you mean.
Do you mean that additional volumetric representations of tissue properties should be addable to the dictionary?
Or that the volumes that are included should be completely customisable?

**Comment by kdreher** [comment]
@leoyala meant that custom volumes can be defined for mua, mus and so on instead of using one of the volume creators. So for example just defining mua as an array full of ones. 
This is actually already possible by defining the volumes, saving them in the standard simpa path and then using the `run_optical_forward_model` function.

**Comment by jgroehl** [comment]
Furthermore, we have the SegmentationMaskLoader that you can use to load segmentation masks and populate the segmentation classes with customised structures.
You could even go so far as to define mua, mus, and g maps and call the run_optical_forward_model without any HDF5 load/save interactions.

**Comment by leoyala** [comment]
> Furthermore, we have the SegmentationMaskLoader that you can use to load segmentation masks and populate the segmentation classes with customised structures.
> You could even go so far as to define mua, mus, and g maps and call the run_optical_forward_model without any HDF5 load/save interactions.

Currently run_optical_model loads the volume properties from the saved HDF5, so it would not work without saving it. Or is this being modified in develop?

**Comment by jgroehl** [comment]
Correct. There needs to be an HDF5 input file. The location of this file is defined via the Settings dictionary.
As long as the file exists, it will be loaded :)

**Comment by jgroehl** [comment]
The volume creator module already saves the HDF5 file.
