### ISSUE TITLE
Fix bandpass filter

### ISSUE THREAD

**Issue by TomTomRixRix** [CAMI-DKFZ/simpa#104]
The bandpass filter currently only filters positive frequencies but not negative ones. This results in all negative frequencies being blocked as no passing band is applied here. Therefore, the signal intensity is lower. To avoid this, we should also implement the filter for negative frequencies and test it.

**Comment by kdreher** [comment]
Resolved by 1286c4c4d4c808eacc300a9ee1586ef59b049225
