### ISSUE TITLE
Remove MITK beamforming support?

### ISSUE THREAD

**Issue by jgroehl** [CAMI-DKFZ/simpa#15]
With the Photoacoustics modules being removed from core MITK and the internal implementations not being generally available, it might be a good idea to also remove MITK beamforming support in SIMPA?

**Comment by kdreher** [comment]
I agree, it becomes more and more difficult to build the MITK beamforming tool, and the current implementation in PyTorch yields comparable results.

**Comment by jgroehl** [comment]
Will remove the adapter when pushing #7 in the end.
