### ISSUE TITLE
Remove dirty loading and saving HDF5 from simulation

### ISSUE THREAD

**Issue by leoyala** [CAMI-DKFZ/simpa#16]
On `simulation.py` the results are loaded and saved consecutively and commented as "dirty fix"

```python
# Quick and dirty fix:
all_data = load_hdf5(settings[Tags.SIMPA_OUTPUT_PATH])
save_hdf5(all_data, settings[Tags.SIMPA_OUTPUT_PATH])
```
This should probably be removed and check that it does not break anything

**Comment by jgroehl** [comment]
With the new changes to the IO system and the new changes to the pipelining system, this will not be needed anymore, I believe.
It was a workaround for how the "extract field of view" method would change the volume, I believe..

**Comment by kdreher** [comment]
Yes, this is intended to decrease the size of our output files. For example, if the extract_field_of_view" method is called, the 3D volumes for absorption, scattering, etc. will be converted to 2D slices and thus. However, in the output file, the memory for the 3D volume has been allocated beforehand which is not decreased automatically when saving the same data field in the same hdf5 file. That is why we load the whole output and then save it again.

But I don't think this issue will be solved with the new pipelining system, is it?

**Comment by jgroehl** [comment]
You are right 🤔
Nevertheless, this IO access at the end of the simulation takes up a large portion of the simulation time for large volumes.

**Comment by kdreher** [comment]
I agree, we definitely need a better solution for this

**Comment by jgroehl** [comment]
@kdreher we could move this behaviour to the new "extract field of view" processing component that can be added optionally to the pipeline.
If and only if the field of view is to be extracted in all saved images, the entire output is loaded and saved again.

Main issue with this solution: scales really badly with multiple wavelength simulations.

**Comment by kdreher** [comment]
The "extract field of view" option will be automatically taken care of when we have a nice solution for defining the field of view of each device. Then, for every 2D probe, the field of view will always be only a 2D array and thus, extracted from a possibly 3-dimensional volume.

**Comment by jgroehl** [comment]
I'm not sure I would opt for a default automatic field of view extraction of the underlying tissue properties. While doing this may be perfectly fine for many applications, it does not allow for later re-simulation of the optical or 3D acoustic forward models.
-> I would suggest making this user-controlled and not part of the device responsibilities.

**Comment by jgroehl** [comment]
IO access times are minimised using compression and in the latest commit to #24, gzip compression now works.
In #24, Per default, the entire file is loaded and saved again, but with a gzip compression. But the user can potentially disable this if it is not wished.

When extracting the fov beforehand, RAM size should not be an issue for handheld simulations when loading all wavelengths at once.

**Comment by jgroehl** [comment]
It is now in the hands of the user whether to use this feature or not by specifying the LOAD_AND_SAVE_HDF5_FILE_AT_THE_END_OF_SIMULATION_TO_MINIMISE_FILESIZE Tag in the settings.
Per default, this is not done, to prefer speed over file size.

**Comment by jgroehl** [comment]
Integrated in #57

**Comment by leoyala** [comment]
> It is now in the hands of the user whether to use this feature or not by specifying the LOAD_AND_SAVE_HDF5_FILE_AT_THE_END_OF_SIMULATION_TO_MINIMISE_FILESIZE Tag in the settings.
> Per default, this is not done, to prefer speed over file size.

Would a shorter tag not be preferable? Something like: `RELOAD_HDF5` and the description of what it does can be added in the Tags class.
