### ISSUE TITLE
Add the posibility to check volumes for general consistency

### ISSUE THREAD

**Issue by leoyala** [CAMI-DKFZ/simpa#17]
It would be beneficial to have a method or class that can check for consistency of volumes before and after simulations are done. Some things that can be checked are listed below.

Before simulations
- [x] All volumes have the same shape
- [x] There are no  `np.nan`, `None`, `np.inf` or negative values in volumes
- [x] #100
- [x] #99

After simulations
- [x] There are no  `np.nan`, `None`, `np.inf` or negative values in volumes
- [x] That volumes have the same shape

**Comment by jgroehl** [comment]
Should this be implemented as a test or as a set of `utils` functions that are available to the user?

We could provide the methods for the user and test them in an integration test.

**Comment by leoyala** [comment]
I think that in general, it would be nice if SIMPA would implement these checks before launching the actual simulations. And then throw a warning in case some checks are not passed. This would put more assurance in the whole pipeline. 
It would propose to integrate it in `utils` and then each `simulation_module` can use it for any type of volume that needs checking.

**Comment by jgroehl** [comment]
What would be the best behaviour in case this does actually happen?
Should the simulations stop and crash with an appropriate error message?
Should the simulations continue and just log a warning?

Probably a crash is the best thing to do. However, this must be properly documented, such that a user can write a batch process accordingly. It would be terrible if simulations don't run through the night, because one volume, in the beginning, had an error.

**Comment by jgroehl** [comment]
"That both volumes Tags.PROPERTY_ABSORPTION_PER_CM and Tags.PROPERTY_SCATTERING_PER_CM are defined in the same regions. It would not make sense to have one set to 0 in a region while the other is different than 0?"

I am not sure I agree with this. In reality, you will probably never have actually 0 absorption or scattering, but there certainly are synthetic cases where you might want to have this.
What is it that you want to test in this case? That each molecular composition provide values for both scattering and absorption? In that case, we might want to add a QA method that does sanity testing for a given molecular composition.
@leoyala please feel free to open an issue if this is what you meant.

**Comment by jgroehl** [comment]
"Add a flag that forces the simulations in case it is desired"

Will include Settings Tag `IGNORE_QA_ASSERTIONS". Standard will be `False` and it should be used in a way that the QA is actually not performed at all if set. This way, this can be USD as a performance optimisation flag.

**Comment by jgroehl** [comment]
If `Tags.IGNORE_QA_ASSERTIONS` is not set to True, the simulation will now always test the following:
- volume creation creates volumes of equal size
- volume creation creates volumes that are not NaN or INF
- optical model will test if fluence and initial pressure are non negative (and do not contain INF or NaN)
- acoustic model creates volumes that are not NaN or INF
- reconstruction model creates volumes that are not NaN or INF
- noise components create volumes that are not NaN or INF

**Comment by jgroehl** [comment]
When running the example scripts, this had no effect on the peformance.

**Comment by jgroehl** [comment]
Pushed to develop with 61e8ca9
