### ISSUE TITLE
Broken test TestMoleculeLibrary

### ISSUE THREAD

**Issue by leoyala** [CAMI-DKFZ/simpa#18]
The test imports the following, but this module is missing in the repo.
```python
from simpa_tests.test_utils import create_test_structure_of_molecule, create_background_of_molecule, set_settings
```

**Comment by jgroehl** [comment]
I just pulled the latest `develop` update and the tests are running fine for me..
All the methods that are being imported are available in the `test_utils` module.
How did you run the test?

**Comment by leoyala** [comment]
Are you sure that the file is pushed to develop? This is how it looks for me in the server.
![Screenshot from 2021-03-19 14-36-06](https://user-images.githubusercontent.com/23067352/111788674-a21f7100-88c0-11eb-8945-ba23d450d1b1.png)

**Comment by jgroehl** [comment]
Yes, the methods apparently were implemented in the __init__.py file.

**Comment by leoyala** [comment]
Ok, you are right, for some reason PyCharm was not discovering it. I am closing this issue.
