### ISSUE TITLE
Missing MCX_SEED Tag

### ISSUE THREAD

**Issue by TomTomRixRix** [CAMI-DKFZ/simpa#2]
At the moment we use the `Tags.MCX_SEED` tag in the `McxAdapter`, but we never defined it:
```python
if Tags.MCX_SEED in settings:
            settings_dict["RNGSeed"] = settings[Tags.MCX_SEED]
```
Is there any sensible default value? Otherwise creating this tag would simply solve the issue.

**Comment by jgroehl** [comment]
We have a Tags.RANDOM_SEED field that seems to fit this purpose.

**Comment by TomTomRixRix** [comment]
I agree, we could use RANDOM_SEED or are there any use cases where a different MCX_SEED is required?

**Comment by jgroehl** [comment]
@kdreher was there a specific reason we introduced a separate number to control the mcx seed independently from the overall random seed?

**Comment by kdreher** [comment]
Yes, we thought it might be interesting to examine photon noise by using different mcx seeds in the same volume.

**Comment by jgroehl** [comment]
why did we remove it then?
I suggest the following to have a sensible default for the seed initialisation:

    if Tags.MCX_SEED not in settings:
        if Tags.RANDOM_SEED in settings:
            settings_dict["RNGSeed"] = settings[Tags.RANDOM_SEED]
    else:
        settings_dict["RNGSeed"] = settings[Tags.MCX_SEED]

**Comment by jgroehl** [comment]
Intergrated into develop
