### ISSUE TITLE
Cross Cutting Concern: Logging

### ISSUE THREAD

**Issue by jgroehl** [CAMI-DKFZ/simpa#21]
SIMPA currently has no internal logging features.
Everything is logged to the command line, without any regard to the severity of the log entry.

We should create a "log" module that can be used to easily get hold of a logger singleton instance.

**Comment by jgroehl** [comment]
Implemented a unified entry-point to the Python 3 logging module for SIMPA. It's ready to be integrated into develop.

**Comment by jgroehl** [comment]
Logging feature was developed in `T21-CentralisedLogging` and is merged into `experimental`.
Would really appreciate a code review @TomTomRixRix @kdreher.

**Comment by TomTomRixRix** [comment]
The logging feature implementation looks good to me. Perhaps it's a good idea to explain the different levels of logging somewhere, e.g. in the `Logger` class. Or simply add a reference to https://docs.python.org/3/howto/logging.html so that everyone knows when to use which level 😄

**Comment by kdreher** [comment]
It also looks fine to me :)
I agree with @TomTomRixRix that an explanation would help to understand the differences of the logging methods.

I only have a minor comment: In the file `file_logger.py` in the docstring for the `Logger` class, the last sentence is incomplete. I guess it is missing its name or the path to where it is stored.

**Comment by jgroehl** [comment]
Pushed into develop.
