### ISSUE TITLE
JSON Settings file

### ISSUE THREAD

**Issue by jgroehl** [CAMI-DKFZ/simpa#22]
There currently is the option to save the settings dictionary as a JSON file in addition to the HDF5 file.
As far as I am aware, however, there is no functionality to start a simulation from a JSON file.

I have the following issues with this:
- There is no functionality to make use of this JSON file integrated within SIMPA.
- With the new pipelining concept, running a simulation just from the settings file is not possible anymore.
- It clutters the simulation.simulate method with a hidden feature.

I propose to remove the JSON saving feature. 
Alternatively, the JSON support should be expanded upon and integrated throughout the pipeline.

**Comment by kdreher** [comment]
The idea behind this was to have a humanly readable form of the settings specified in the hdf5 output file. I agree that otherwise, it has no functionality for that, so I also agree to remove this feature.

**Comment by jgroehl** [comment]
Implement feature to load JSON settings file and start simulation

**Comment by jgroehl** [comment]
I see two options:
- have a `start_from_json(pipeline: list, path_to_json: str)` method in the `simpa.core.simulate` module
- have a `load_settings(json_path: str) -> Settings` method in the `simpa.io_handling` module

I prefer the second option.

**Comment by jgroehl** [comment]
Removed feature in the current stable branch #57 in case it is ever needed, the last working state of this code can be found in 3917a93b3087ed634e2beccc93ffa9c2edd018b5
