### ISSUE TITLE
Integration of USABLE PA devices

### ISSUE THREAD

**Issue by jgroehl** [CAMI-DKFZ/simpa#24]
It is currently not visible to the user that the provided probe designs require a special mcx version that is not available to work.

- [x] Linear Array
- [x] Curved Array 
- [x] Re-implement Acuity system
- [x] Re-implement RSOM system
- [x] Re-implement InVision system
- [x] Create a fork of mcx that contains the probe specifications for everyone to use

**Comment by kdreher** [comment]
We should implement default illumination and detection devices separately and an additional PA device generator that takes one illumination and one detection device from our predefined devices and generates the respective PA device.
This way, users have a lot more choices to construct a PA device "on the fly". Also, it is more elegant to just simulate the optical or acoustic models without having to choose a PA device when there is no PA effect involved.

Specific products like the MSOT devices can still stay the way they are.

**Comment by jgroehl** [comment]
It might be worth considering creating new classes for the `DetectionGeometry` and `IlluminationGeometry` and having a `PADevice` class that is a combination of the two?
The settings file would then be assigned the PADevice instance, where one of the two could be `None` thus achieving what you propose?

**Comment by jgroehl** [comment]
Potentially found an "off-by-one" error in the Python to MATLAB conversion when defining the detector positions. MATLAB indexing starts with 1, not 0, which we apparently did not consider previously.

**Comment by jgroehl** [comment]
Work on this will also fix #49.

**Comment by jgroehl** [comment]
Linear and curved detection geometries are now implemented.

**Comment by jgroehl** [comment]
Implemented all previously available devices.
Custom devices that combine the illumination and detection geometries can now easily be added.

@kdreher I propose we discuss the current implementation, integrate it into develop and start adding more detection and illumination geometries in a new task.

**Comment by jgroehl** [comment]
Will work towards #19 and #12 within these changes

**Comment by jgroehl** [comment]
Opened new task #61 for the addition of further geometries that should be in SIMPA.
Closing, as it is integrated in #57
