### ISSUE TITLE
Flipping error

### ISSUE THREAD

**Issue by TomTomRixRix** [CAMI-DKFZ/simpa#27]
It seems as if we currently have a flipping error in the simulation pipeline which might occur because MATLAB is indexing in another way than numpy/python. This error doesn't occur when reconstructing real photoacoustic images, only when reconstructing simulated ones. Thus we should solve it when calling the MATLAB code and before the reconstruction. For me a simple left/right flip of the reconstructed image solved the issue.

**Comment by kdreher** [comment]
Should be fixed with #54
