### ISSUE TITLE
Redundancy in segmentation loader

### ISSUE THREAD

**Issue by kdreher** [CAMI-DKFZ/simpa#36]
Currently, the segmentation loader saves the input segmentation twice. Once in the settings and once again in the simulation properties. This unnecessarily increases the savefile size. I think we should remove the array in the settings.

**Comment by jgroehl** [comment]
Is this fixed already?

**Comment by jgroehl** [comment]
👀

**Comment by kdreher** [comment]
It is fixed now, sorry for the long waiting time
