### ISSUE TITLE
Modules versus components naming conventions

### ISSUE THREAD

**Issue by jgroehl** [CAMI-DKFZ/simpa#37]
Currently, our module and component naming conventions are a mess.
I propose the following naming convention:

Any module adapter has to have the following naming convention:
- {PURPOSE}Module{FRAMEWORK}Adapter
- For example: OpticalModuleMcxAdapter or AcousticModuleKWaveAdapter

Any processing component has to have the following naming convention:
- {DESCRIPTION}ProcessingComponent
- For example: LinearUnmixingProcessingComponent or GaussianNoiseProcessingComponent

This way, all framework adapters for the modules and all processing components are easily identifiable as such.

**Comment by jgroehl** [comment]
@kdreher what do you think?

**Comment by kdreher** [comment]
I agree
