### ISSUE TITLE
Ugly case-specific axes definitions and volume manipulations

### ISSUE THREAD

**Issue by jgroehl** [CAMI-DKFZ/simpa#38]
https://github.com/CAMI-DKFZ/simpa/blob/19114b55857468d0f2b406fa150f1306ff022326/simpa/core/acoustic_simulation/k_wave_adapter.py#L90-L102

We should try and find a cleaner way to do this and properly document why this is done..
Why are some volumes modified with fliplr and rot90 and other only with rot90(-3)? Is this really equivalent?

**Comment by kdreher** [comment]
The arrays that come out of the mcx adapter are not oriented the same way as before. That is why properties like density are rotated differently than the initial pressure. I agree that this behaviour is a bug that should be solved by the mcx adapter.

**Comment by jgroehl** [comment]
I believe this should be fixed on `develop`, will check..

**Comment by jgroehl** [comment]
Yes, all fields are handled equally now. Closing...
