### ISSUE TITLE
Detector definition in 2D acoustic simulation causes k-Wave error

### ISSUE THREAD

**Issue by kdreher** [CAMI-DKFZ/simpa#42]
Using the [optical_and_acoustic_simulation](https://github.com/CAMI-DKFZ/simpa/blob/develop/simpa_examples/optical_and_acoustic_simulation.py) and setting the ACOUSTIC_SIMULATION_3D Tag to False causes this error: sensor.mask cuboid corners must be within the grid.

This error is probably due to the way the detector definition in the [acoustic_forward_module_k_wave_adapter](https://github.com/CAMI-DKFZ/simpa/blob/develop/simpa/core/acoustic_forward_module/acoustic_forward_module_k_wave_adapter.py) is done.

**Comment by jgroehl** [comment]
Will revert to the "old" definition of the detectors and temporarily save an index matrix that can be used later to correctly merge and sort the resulting time-series data.

**Comment by jgroehl** [comment]
Will be fixed with #54
