### ISSUE TITLE
Refactor Delay-And-Sum Implementation

### ISSUE THREAD

**Issue by jgroehl** [CAMI-DKFZ/simpa#5]
- move pre- post-processing to "processing" from the reconstruction module
- 3D implementation
- extract field of view from device

**Comment by TomTomRixRix** [comment]
At the moment some functions use numpy arrays others torch tensors. In particular, pre- and post-processing is done in numpy while functions used during reconstruction require torch tensors. It might be worth providing all functions for both, numpy arrays and torch tensors, if possible.

**Comment by TomTomRixRix** [comment]
Regarding the field of view from device: Given the suggested implementation as a list as in #11, one could implement an abstract function `get_field_of_view()` which must be implemented by each device. This function can then be used in the reconstruction algorithm for determining the dimensions of the reconstructed image like this:
```python
field_of_view = pa_device.get_field_of_view()
xdim = field_of_view[1]-field_of_view[0]/sensor_spacing_in_mm
ydim = field_of_view[3]-field_of_view[2]/sensor_spacing_in_mm
zdim = field_of_view[5]-field_of_view[4]/sensor_spacing_in_mm
```

As a backup, e.g. if the function returns `None` or raises an exception one could use the current computation of the reconstruction size.

**Comment by TomTomRixRix** [comment]
@jgroehl @kdreher All features except of the field of view are implemented and ready for review on branch `T28377-improved-DAS` (still having the old naming convention 😕). There are also some small design questions that may be discussed, so having a short meeting would be cool.

**Comment by kdreher** [comment]
I had a look at the code and I have only minor comments:

`PyTorchDASAdapter.py`:
- l88 It should be checked for the device position in the settings and only if it is not given by the user, set it to the default value
- l167 remove redundant parentheses
- l178 we should only get an apodization factor if it is specified in the settings -> move this code block to l188 when the apodization is used and only multiply with the values if it is given in the settings. Thus, we can save one matrix multiplication with only ones (output of `get_apodization_factor` if no apodization is given)
- l207 function names should be lowercase

`signal_processing.py`:
- l95 variable names should be lowercase

Finally, also add the `TestProcessing.py` file to the framework tests in `do_coverage.py`
