### ISSUE TITLE
Reloading settings of previous run and starting a new simulation doesn't work 

### ISSUE THREAD

**Issue by kdreher** [CAMI-DKFZ/simpa#51]
When running a simulation, the settings are saved in the output file. Reloading these settings and starting a new simulation doesn't work as some keys in the settings can't be found anymore.

**Comment by jgroehl** [comment]
Is there a test to automatically test for saving and loading of a complete theoretically functioning settings file?
If not, we should definitely write one to avoid these problems in the future.
What do you think @kdreher?
