### ISSUE TITLE
Fix Acuity Echo setup after recent changes to the device definitions

### ISSUE THREAD

**Issue by jgroehl** [CAMI-DKFZ/simpa#52]

**Comment by TomTomRixRix** [comment]
Solved on branch `T52-FixAcuityEcho` and merged into `T24-PADevicesIntegration`, resolving #24. Also includes using the field of view definition of PA devices in reconstruction algorithm as mentioned in #5.

**Comment by kdreher** [comment]
There is still an issue as the detection geometry still looks like a semicircle

**Comment by kdreher** [comment]
The issue was a wrong pitch in the detector geometry, but it should be resolved now in `T24-PADevicesIntegration` as mentioned by @TomTomRixRix
