### ISSUE TITLE
Integrate new kWaveArray class

### ISSUE THREAD

**Issue by kdreher** [CAMI-DKFZ/simpa#54]
The new kWaveArray class seems promising as a standardized way to define our detector geometries in k-Wave.

**Comment by jgroehl** [comment]
After copy pasting the source files from 
http://www.k-wave.org/forum/topic/alpha-version-of-kwavearray-off-grid-sources
I also needed to run 
`rehash toolbox` in MATLAB

**Comment by TomTomRixRix** [comment]
Perhaps it's a good idea to mention the `rehash toolbox` trick in the installation guide under troubleshooting or something so that if someone else has the same problem that they don't have to find the solution in this issue but in the installation guide
