### ISSUE TITLE
Use scattering coefficient spectra in tissue definitions

### ISSUE THREAD

**Issue by mschllnbrg** [CAMI-DKFZ/simpa#56]
Change the definition of tissues in the following way: 

1. fit the power law on literature spectra
2. use fitted values (scattering coefficient spectrum) directly in definitions of tissue

**Comment by jgroehl** [comment]
Currently, scattering is by default defined via a power law fit.
However, to homogenise this with the implementation of absorption and anisotropy, it might be a good idea to also represent scattering as a `Spectrum` .
We should consider a convenience function that calculates the respective scattering spectrum from the parameters of a power law fit.

**Comment by jgroehl** [comment]
Implemented and currently merged into #40
