### ISSUE TITLE
Correct field of view defintions

### ISSUE THREAD

**Issue by kdreher** [CAMI-DKFZ/simpa#64]
The field-of-view definitions are currently not correct. For example, for a linear array, the skin layer isn't visible in the reconstructed image.

**Comment by jgroehl** [comment]
The field of view of the Acuity Echo is not defined correctly.
It needs to be examined if the skin layer invisibility is indeed related to the field of view or to another reason.

**Comment by jgroehl** [comment]
Fixed this when pushing #69
