### ISSUE TITLE
Errors in spectral_library

### ISSUE THREAD

**Issue by Holzwarth69126** [CAMI-DKFZ/simpa#68]
- Different absorbers have to be instanced in a particular order (lack of usability)
- Does it make sense, that the spectral library is defined as class?
- The spectra should be appended to 1100nm, if possible to match PA device.
- Error handling not intuitive.

**Comment by jgroehl** [comment]
We should, in general, move to file-based spectra again.
Currently the spectra are hard coded and could instead easily be loaded from disk.

**Comment by jgroehl** [comment]
File-based spectra are implemented.
The SpectraLibrary class is not just a convenience class to easily load and iterate over all available spectra.
The spectra can be used completely independently of this class by using the `Spectrum` class.

The errors explicitly say if a spectrum can't be resolved by its name.

**Comment by jgroehl** [comment]
The spectra can easily be extended by changing the respective .npy files with versions that have an extended wavelength range.
