### ISSUE TITLE
Linear Unmixing Test Coverage too low

### ISSUE THREAD

**Issue by jgroehl** [CAMI-DKFZ/simpa#83]
Currently, LU test coverage is ~14%, which is too low for a python-only component.

**Comment by jgroehl** [comment]
test invalid wavelengths

**Comment by jgroehl** [comment]
@TomTomRixRix I'd like to refactor the linear unmixing code at some point (#82). Are your changes to the tests pushable, or could you tell me the branch you are working on for this?

**Comment by TomTomRixRix** [comment]
The code should be ready to merge on branch `T83-TestCoverageLinearUnmixing`. However, as mentioned on Friday, the branch `T95-NNLS_LinearUnmixing` should probably be merged first into T83.

**Comment by jgroehl** [comment]
changes merged into develop. Follow #82 for further updates
