### ISSUE TITLE
Fix SIMPA API conventions

### ISSUE THREAD

**Issue by jgroehl** [CAMI-DKFZ/simpa#89]
- [x] The differentiation between `algorithms` with `monospectral` vs. `multispectral` and the `core` modules and packages such as the `ProcessingComponents` is not intuitive. When looking for a certain functionality it is not clear where to find these. It is also not clear for a developer where to integrate new features...
- [x] Data fields are not named consistently (should be DATA_FIELD_XYZ)
- [x] Enable top level simpa import: `import siimpa as sp`
- [x] Shorten import path names from simpa to top level names for any "public API" classes of the tool
- [x] Shorten class names to the minimal working version
- [x] The Tag `LOAD_AND_SAVE_HDF5_FILE_AT_THE_END_OF_SIMULATION_TO_MINIMISE_FILESIZE` should rather be `Tags.DO_FILE_COMPRESSION`
- [x] Refactor internal core module structure
- [ ] Refactor FOV API
- [x] make sure illumination properties are set automatically

**Comment by jgroehl** [comment]
- [ ] The differentiation between `algorithms` with `monospectral` vs. `multispectral` and the `core` modules and packages such as the `ProcessingComponents` is not intuitive. When looking for a certain functionality it is not clear where to find these. It is also not clear for a developer where to integrate new features...

**Comment by jgroehl** [comment]
Copy of external feedback:

imports at the top of the file tend to get quite long, at least in the examples. So you end up having to import every single class separately. 
It would be great if you could do something like:
`import simpa as sp`
Then refer to all classes as `sp._____`
The classes tend to have quite long names too so maybe they could be a bit shorter.

**Comment by jgroehl** [comment]
This (https://github.com/CAMI-DKFZ/simpa/issues/89#issuecomment-911432765) would mean that we would have to design a top-level __init__.py that enables this sort of import.

**Comment by TomTomRixRix** [comment]
In general it would be nice to have shorter imports, e.g. instead of
```python
from simpa.core.acoustic_forward_module.acoustic_forward_module_k_wave_adapter import AcousticForwardModelKWaveAdapter
from simpa.core.optical_simulation_module.optical_forward_model_mcx_adapter import OpticalForwardModelMcxAdapter
from simpa.core.reconstruction_module.reconstruction_module_delay_and_sum_adapter import \
    ImageReconstructionModuleDelayAndSumAdapter
```
something like
```python
from simpa.core.acoustic_forward_module import AcousticForwardModelKWaveAdapter
from simpa.core.optical_simulation_module import OpticalForwardModelMcxAdapter
from simpa.core.reconstruction_module import ImageReconstructionModuleDelayAndSumAdapter
```
or even better
```python
from simpa import AcousticForwardModelKWaveAdapter
from simpa import OpticalForwardModelMcxAdapter
from simpa import ImageReconstructionModuleDelayAndSumAdapter
```
As the module a class belongs to is always mentioned in the class name, it should not be a problem to leave out the long module path imo.

**Comment by TomTomRixRix** [comment]
I find a bit confusing that the `device_digital_twins` folder is in the same directory as all the simulation modules. For me it makes sense to have both in the `core` module, but I would prefer a structure like this:
```
core/
  device_digital_twins/
     illumination_geometries/
     detection_geometries/
     pa_devices/
  simulation_modules/
     optical_forward_module/
     acoustic_forward_module/
     ...
     volume_creation_module/
     simulation.py
```

**Comment by jgroehl** [comment]
Both the PhotoacousticDevice and the DetectionGeometry have field of view definitions that do have to agree and it is not clear which one is used where and which one the user needs to set.

**Comment by pvieten** [comment]
The fourier transformation used for bandpass filtering seems to corrupt the reconstructions when applied to real images (fourier(fourier(image))!=image). For example when setting the cutoff frequencies to 0 and inf the images are still blurred. I have created Issue #93 to address this problem.

**Comment by mschllnbrg** [comment]
It is not intuitive when device-specific volume components, such as membrane, heavy water, etc., are created within the volume and when not.

For example: In optical forward simulations using 
a. VolumeCreationModelModelBasedAdapter or 
b. VolumeCreationModuleSegmentationBasedAdapter,
the optical settings can be set to Tags.ILLUMINATION_TYPE: Tags.ILLUMINATION_TYPE_MSOT_ACUITY_ECHO.

However, in case a), the MSOT device needs to be specified and updated (which is in my opinion a bit unintuitive)
device = MSOTAcuityEcho(...)
device.update_settings_for_use_of_model_based_volume_creator(settings)

such that the device specifics are created by the VolumeCreationModelModelBasedAdapter. In case b) this is not required for the VolumeCreationModuleSegmentationBasedAdapter.

**Comment by jgroehl** [comment]
@mschllnbrg The illumination should automatically be used correctly without having to specify the device in the settings.
I'll add this to the checklist.

The issue with the settings update for the model-based volume creator was discussed before and we did not find a nice solution. Open to any suggestions.

**Comment by jgroehl** [comment]
The suggested changes are now all merged into `develop`.
