### ISSUE TITLE
Trailing slashes in env paths

### ISSUE THREAD

**Issue by TomTomRixRix** [CAMI-DKFZ/simpa#94]
In the example config file `simpa_examples/path_config.env` we suggest the following SAVE_PATH
`SAVE_PATH= /workplace/data/ `

However, the trailing slash leads to a double`//` in some cases. We should either suggest providing paths without trailing slashes or remove it automatically within the path manager to avoid problems. Ideally we would do both 😄

**Comment by kdreher** [comment]
Resolved by 616d08f8570ffd1de3b40577558b4063aad2e139
