### ISSUE TITLE
Linear Unmixing Non Negative Constraint

### ISSUE THREAD

**Issue by pvieten** [CAMI-DKFZ/simpa#95]
Integration of non negative linear unmixing using:
from scipy.optimize import nnls

**Comment by jgroehl** [comment]
@pvieten I saw you already merged with the previous version of `develop` on Friday. Would it be okay for me to review the code and merge this with #83 and the current `develop`?

I would then push into `develop`, close #95 and #83 and then work on a refactored version of the code in #82.

**Comment by jgroehl** [comment]
Changes pushed into develop. Follow #82 for further updates.
