### ISSUE TITLE
That both volumes `Tags.PROPERTY_ABSORPTION_PER_CM` and `Tags.PROPERTY_SCATTERING_PER_CM` are defined in the same regions. It would not make sense to have one set to 0 in a region while the other is different than 0?

### ISSUE THREAD

**Issue by jgroehl** [CAMI-DKFZ/simpa#99]

**Comment by leoyala** [comment]
I think that it is just our hope that the volume creator would not generate volumes with such incompatibilities, but I think that it is still a worth doing test before launching the simulations. This might also become relevant when the user created the volumes themselves.
